# Generated by Django 5.2.1 on 2025-09-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_testimonial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='save_comments',
            field=models.BooleanField(default=False),
        ),
    ]
