# Generated by Django 5.2.1 on 2025-09-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blogcomment_save_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
